### ISSUE TITLE
Who do you choose ForTheThrone insert 

### ISSUE THREAD

**Issue by goldbergtatyana** [Arathrix/JS19_GroupD#2]
This insert is brilliant, however disappears when mouse is hovered over one of the characters and does not appear again. I wish to see it again when the mouse is not located over a character, i.e. they both are at their initial place

**Comment by Arathrix** [comment]
That was actually a design decision (to hide it) as we wanted to bring forward a description about the project. The initial box with #ForTheThrone is just there to get people to hover over.

**Comment by Arathrix** [comment]
implemented
