### ISSUE TITLE
Death status comparison logic problem

### ISSUE THREAD

**Issue by gyachdav** [Arathrix/JS19_GroupD#21]
https://gotshow.herokuapp.com/characters/Sandor%20Clegane

Something in the logic seems to be off

![image](https://user-images.githubusercontent.com/4074881/55670006-47cda700-5887-11e9-8095-cf271127eb73.png)

**Comment by Arathrix** [comment]
fixed, will be online

**Comment by Arathrix** [comment]
fixed
