### ISSUE TITLE
Carussel for all favorite characters

### ISSUE THREAD

**Issue by goldbergtatyana** [Arathrix/JS19_GroupD#5]
It seems to me that the only way to read about main characters is by clicking on their icons in 'Discover your favorite character's chance of survival now!'. Right now this section lists only 5 characters, but I would like to read about all of them. So, could we have arrows on each of the sides to allow me to go over all characters?

**Comment by Arathrix** [comment]
Great idea and simple to implement - we'll get on it

**Comment by Arathrix** [comment]
implemented
