### ISSUE TITLE
wiki button in character page

### ISSUE THREAD

**Issue by gyachdav** [Arathrix/JS19_GroupD#6]
The wiki button in the character page can go away as we are now  using two wiki sources. 

Instead of this button create a link to the appropriate character page in the book/tv wiki where it says book/TV show

**Comment by Arathrix** [comment]
Perhaps we can have 2 buttons? in I would estimate ~10 % of the cases we have both sources, so each button can be hidden if the source isn't available.

**Comment by gyachdav** [comment]
I'm not in favor having many buttons in the page. less buttons keep the page cleaner. Since you already have the text "TV show" or "Book" in the character page, just use it to serve as a link.

**Comment by Arathrix** [comment]
Ah that can be done

**Comment by Arathrix** [comment]
implemented
